version: "3"
services:
  tests:
    build: .
    command: npm test
  app:
    restart: on-failure
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - PGHOST=db
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=anicepassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  db:
    driver: "local"
